//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormBinhPhu.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/xphu")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idaccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idacc {
            get {
                return this.idaccField;
            }
            set {
                if ((object.ReferenceEquals(this.idaccField, value) != true)) {
                    this.idaccField = value;
                    this.RaisePropertyChanged("idacc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool role {
            get {
                return this.roleField;
            }
            set {
                if ((this.roleField.Equals(value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Option", Namespace="http://schemas.datacontract.org/2004/07/xphu")]
    [System.SerializableAttribute()]
    public partial class Option : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime deadlinetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idoptField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contents {
            get {
                return this.contentsField;
            }
            set {
                if ((object.ReferenceEquals(this.contentsField, value) != true)) {
                    this.contentsField = value;
                    this.RaisePropertyChanged("contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deadlinetime {
            get {
                return this.deadlinetimeField;
            }
            set {
                if ((this.deadlinetimeField.Equals(value) != true)) {
                    this.deadlinetimeField = value;
                    this.RaisePropertyChanged("deadlinetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idopt {
            get {
                return this.idoptField;
            }
            set {
                if ((object.ReferenceEquals(this.idoptField, value) != true)) {
                    this.idoptField = value;
                    this.RaisePropertyChanged("idopt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vote", Namespace="http://schemas.datacontract.org/2004/07/xphu")]
    [System.SerializableAttribute()]
    public partial class Vote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idaccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idoptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idvoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool flag {
            get {
                return this.flagField;
            }
            set {
                if ((this.flagField.Equals(value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idacc {
            get {
                return this.idaccField;
            }
            set {
                if ((object.ReferenceEquals(this.idaccField, value) != true)) {
                    this.idaccField = value;
                    this.RaisePropertyChanged("idacc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idopt {
            get {
                return this.idoptField;
            }
            set {
                if ((object.ReferenceEquals(this.idoptField, value) != true)) {
                    this.idoptField = value;
                    this.RaisePropertyChanged("idopt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idvote {
            get {
                return this.idvoteField;
            }
            set {
                if ((object.ReferenceEquals(this.idvoteField, value) != true)) {
                    this.idvoteField = value;
                    this.RaisePropertyChanged("idvote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsAcount", ReplyAction="http://tempuri.org/IService1/DsAcountResponse")]
        System.Data.DataSet DsAcount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsAcount", ReplyAction="http://tempuri.org/IService1/DsAcountResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DsAcountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DangNhap", ReplyAction="http://tempuri.org/IService1/DangNhapResponse")]
        bool DangNhap(FormBinhPhu.ServiceReference1.Account userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DangNhap", ReplyAction="http://tempuri.org/IService1/DangNhapResponse")]
        System.Threading.Tasks.Task<bool> DangNhapAsync(FormBinhPhu.ServiceReference1.Account userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Account", ReplyAction="http://tempuri.org/IService1/AccountResponse")]
        bool Account(FormBinhPhu.ServiceReference1.Account userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Account", ReplyAction="http://tempuri.org/IService1/AccountResponse")]
        System.Threading.Tasks.Task<bool> AccountAsync(FormBinhPhu.ServiceReference1.Account userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemAc", ReplyAction="http://tempuri.org/IService1/ThemAcResponse")]
        bool ThemAc(FormBinhPhu.ServiceReference1.Account them);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemAc", ReplyAction="http://tempuri.org/IService1/ThemAcResponse")]
        System.Threading.Tasks.Task<bool> ThemAcAsync(FormBinhPhu.ServiceReference1.Account them);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaAc", ReplyAction="http://tempuri.org/IService1/SuaAcResponse")]
        bool SuaAc(FormBinhPhu.ServiceReference1.Account sua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaAc", ReplyAction="http://tempuri.org/IService1/SuaAcResponse")]
        System.Threading.Tasks.Task<bool> SuaAcAsync(FormBinhPhu.ServiceReference1.Account sua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaAc", ReplyAction="http://tempuri.org/IService1/XoaAcResponse")]
        bool XoaAc(FormBinhPhu.ServiceReference1.Account xoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaAc", ReplyAction="http://tempuri.org/IService1/XoaAcResponse")]
        System.Threading.Tasks.Task<bool> XoaAcAsync(FormBinhPhu.ServiceReference1.Account xoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemOption", ReplyAction="http://tempuri.org/IService1/ThemOptionResponse")]
        bool ThemOption(FormBinhPhu.ServiceReference1.Option them);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemOption", ReplyAction="http://tempuri.org/IService1/ThemOptionResponse")]
        System.Threading.Tasks.Task<bool> ThemOptionAsync(FormBinhPhu.ServiceReference1.Option them);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaOption", ReplyAction="http://tempuri.org/IService1/XoaOptionResponse")]
        bool XoaOption(FormBinhPhu.ServiceReference1.Option xoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaOption", ReplyAction="http://tempuri.org/IService1/XoaOptionResponse")]
        System.Threading.Tasks.Task<bool> XoaOptionAsync(FormBinhPhu.ServiceReference1.Option xoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsContents", ReplyAction="http://tempuri.org/IService1/DsContentsResponse")]
        System.Data.DataSet DsContents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsContents", ReplyAction="http://tempuri.org/IService1/DsContentsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DsContentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsAns", ReplyAction="http://tempuri.org/IService1/DsAnsResponse")]
        System.Data.DataSet DsAns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsAns", ReplyAction="http://tempuri.org/IService1/DsAnsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DsAnsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadContent", ReplyAction="http://tempuri.org/IService1/LoadContentResponse")]
        bool LoadContent(FormBinhPhu.ServiceReference1.Vote vote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadContent", ReplyAction="http://tempuri.org/IService1/LoadContentResponse")]
        System.Threading.Tasks.Task<bool> LoadContentAsync(FormBinhPhu.ServiceReference1.Vote vote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsOption", ReplyAction="http://tempuri.org/IService1/DsOptionResponse")]
        System.Data.DataSet DsOption();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsOption", ReplyAction="http://tempuri.org/IService1/DsOptionResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DsOptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsCode", ReplyAction="http://tempuri.org/IService1/DsCodeResponse")]
        System.Data.DataSet DsCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DsCode", ReplyAction="http://tempuri.org/IService1/DsCodeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DsCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaVote", ReplyAction="http://tempuri.org/IService1/SuaVoteResponse")]
        bool SuaVote(FormBinhPhu.ServiceReference1.Vote sua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaVote", ReplyAction="http://tempuri.org/IService1/SuaVoteResponse")]
        System.Threading.Tasks.Task<bool> SuaVoteAsync(FormBinhPhu.ServiceReference1.Vote sua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemVote", ReplyAction="http://tempuri.org/IService1/ThemVoteResponse")]
        bool ThemVote(FormBinhPhu.ServiceReference1.Vote them);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemVote", ReplyAction="http://tempuri.org/IService1/ThemVoteResponse")]
        System.Threading.Tasks.Task<bool> ThemVoteAsync(FormBinhPhu.ServiceReference1.Vote them);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaOption", ReplyAction="http://tempuri.org/IService1/SuaOptionResponse")]
        bool SuaOption(FormBinhPhu.ServiceReference1.Option sua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaOption", ReplyAction="http://tempuri.org/IService1/SuaOptionResponse")]
        System.Threading.Tasks.Task<bool> SuaOptionAsync(FormBinhPhu.ServiceReference1.Option sua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Idacc", ReplyAction="http://tempuri.org/IService1/IdaccResponse")]
        bool Idacc(FormBinhPhu.ServiceReference1.Vote timid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Idacc", ReplyAction="http://tempuri.org/IService1/IdaccResponse")]
        System.Threading.Tasks.Task<bool> IdaccAsync(FormBinhPhu.ServiceReference1.Vote timid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Dsopt", ReplyAction="http://tempuri.org/IService1/DsoptResponse")]
        System.Data.DataSet Dsopt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Dsopt", ReplyAction="http://tempuri.org/IService1/DsoptResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DsoptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Luotvote", ReplyAction="http://tempuri.org/IService1/LuotvoteResponse")]
        System.Data.DataSet Luotvote();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Luotvote", ReplyAction="http://tempuri.org/IService1/LuotvoteResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> LuotvoteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapnhatFlag", ReplyAction="http://tempuri.org/IService1/CapnhatFlagResponse")]
        bool CapnhatFlag(FormBinhPhu.ServiceReference1.Vote flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapnhatFlag", ReplyAction="http://tempuri.org/IService1/CapnhatFlagResponse")]
        System.Threading.Tasks.Task<bool> CapnhatFlagAsync(FormBinhPhu.ServiceReference1.Vote flag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FormBinhPhu.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FormBinhPhu.ServiceReference1.IService1>, FormBinhPhu.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DsAcount() {
            return base.Channel.DsAcount();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DsAcountAsync() {
            return base.Channel.DsAcountAsync();
        }
        
        public bool DangNhap(FormBinhPhu.ServiceReference1.Account userinfo) {
            return base.Channel.DangNhap(userinfo);
        }
        
        public System.Threading.Tasks.Task<bool> DangNhapAsync(FormBinhPhu.ServiceReference1.Account userinfo) {
            return base.Channel.DangNhapAsync(userinfo);
        }
        
        public bool Account(FormBinhPhu.ServiceReference1.Account userinfo) {
            return base.Channel.Account(userinfo);
        }
        
        public System.Threading.Tasks.Task<bool> AccountAsync(FormBinhPhu.ServiceReference1.Account userinfo) {
            return base.Channel.AccountAsync(userinfo);
        }
        
        public bool ThemAc(FormBinhPhu.ServiceReference1.Account them) {
            return base.Channel.ThemAc(them);
        }
        
        public System.Threading.Tasks.Task<bool> ThemAcAsync(FormBinhPhu.ServiceReference1.Account them) {
            return base.Channel.ThemAcAsync(them);
        }
        
        public bool SuaAc(FormBinhPhu.ServiceReference1.Account sua) {
            return base.Channel.SuaAc(sua);
        }
        
        public System.Threading.Tasks.Task<bool> SuaAcAsync(FormBinhPhu.ServiceReference1.Account sua) {
            return base.Channel.SuaAcAsync(sua);
        }
        
        public bool XoaAc(FormBinhPhu.ServiceReference1.Account xoa) {
            return base.Channel.XoaAc(xoa);
        }
        
        public System.Threading.Tasks.Task<bool> XoaAcAsync(FormBinhPhu.ServiceReference1.Account xoa) {
            return base.Channel.XoaAcAsync(xoa);
        }
        
        public bool ThemOption(FormBinhPhu.ServiceReference1.Option them) {
            return base.Channel.ThemOption(them);
        }
        
        public System.Threading.Tasks.Task<bool> ThemOptionAsync(FormBinhPhu.ServiceReference1.Option them) {
            return base.Channel.ThemOptionAsync(them);
        }
        
        public bool XoaOption(FormBinhPhu.ServiceReference1.Option xoa) {
            return base.Channel.XoaOption(xoa);
        }
        
        public System.Threading.Tasks.Task<bool> XoaOptionAsync(FormBinhPhu.ServiceReference1.Option xoa) {
            return base.Channel.XoaOptionAsync(xoa);
        }
        
        public System.Data.DataSet DsContents() {
            return base.Channel.DsContents();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DsContentsAsync() {
            return base.Channel.DsContentsAsync();
        }
        
        public System.Data.DataSet DsAns() {
            return base.Channel.DsAns();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DsAnsAsync() {
            return base.Channel.DsAnsAsync();
        }
        
        public bool LoadContent(FormBinhPhu.ServiceReference1.Vote vote) {
            return base.Channel.LoadContent(vote);
        }
        
        public System.Threading.Tasks.Task<bool> LoadContentAsync(FormBinhPhu.ServiceReference1.Vote vote) {
            return base.Channel.LoadContentAsync(vote);
        }
        
        public System.Data.DataSet DsOption() {
            return base.Channel.DsOption();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DsOptionAsync() {
            return base.Channel.DsOptionAsync();
        }
        
        public System.Data.DataSet DsCode() {
            return base.Channel.DsCode();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DsCodeAsync() {
            return base.Channel.DsCodeAsync();
        }
        
        public bool SuaVote(FormBinhPhu.ServiceReference1.Vote sua) {
            return base.Channel.SuaVote(sua);
        }
        
        public System.Threading.Tasks.Task<bool> SuaVoteAsync(FormBinhPhu.ServiceReference1.Vote sua) {
            return base.Channel.SuaVoteAsync(sua);
        }
        
        public bool ThemVote(FormBinhPhu.ServiceReference1.Vote them) {
            return base.Channel.ThemVote(them);
        }
        
        public System.Threading.Tasks.Task<bool> ThemVoteAsync(FormBinhPhu.ServiceReference1.Vote them) {
            return base.Channel.ThemVoteAsync(them);
        }
        
        public bool SuaOption(FormBinhPhu.ServiceReference1.Option sua) {
            return base.Channel.SuaOption(sua);
        }
        
        public System.Threading.Tasks.Task<bool> SuaOptionAsync(FormBinhPhu.ServiceReference1.Option sua) {
            return base.Channel.SuaOptionAsync(sua);
        }
        
        public bool Idacc(FormBinhPhu.ServiceReference1.Vote timid) {
            return base.Channel.Idacc(timid);
        }
        
        public System.Threading.Tasks.Task<bool> IdaccAsync(FormBinhPhu.ServiceReference1.Vote timid) {
            return base.Channel.IdaccAsync(timid);
        }
        
        public System.Data.DataSet Dsopt() {
            return base.Channel.Dsopt();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DsoptAsync() {
            return base.Channel.DsoptAsync();
        }
        
        public System.Data.DataSet Luotvote() {
            return base.Channel.Luotvote();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LuotvoteAsync() {
            return base.Channel.LuotvoteAsync();
        }
        
        public bool CapnhatFlag(FormBinhPhu.ServiceReference1.Vote flag) {
            return base.Channel.CapnhatFlag(flag);
        }
        
        public System.Threading.Tasks.Task<bool> CapnhatFlagAsync(FormBinhPhu.ServiceReference1.Vote flag) {
            return base.Channel.CapnhatFlagAsync(flag);
        }
    }
}
